INSERT INTO resources
    (owner_id, category_id, content_type, title, description, url)
VALUES
    (1, 1, 'Article', 'Introduction: callbacks', 'Many actions in JavaScript are asynchronous. In other words, we initiate them now, but they finish later.', 'https://javascript.info/callbacks'),
    (1, 2, 'Article', 'rem vs em in CSS?', 'Difference between em and rem in css', 'https://stackoverflow.com/questions/13941275/how-does-rem-differ-from-em-in-css'),
    (2, 1, 'Online Course', 'Computer programming', 'Comprehensive program, free of charge from Khan Academy.', 'https://www.khanacademy.org/computing/computer-programming'),
    (2, 1, 'Article', 'Array.map()', 'Basic intro to the array map function.', 'https://www.w3schools.com/jsref/jsref_map.asp'),
    (1, 1, 'Article', 'Javascript Style Guide', 'How to write javascript with correct style.', 'https://github.com/airbnb/javascript'),
    (1, 2, 'Article', 'Positioning methods in CSS', 'Overview of the different methods to position elements in css.', 'https://learn.shayhowe.com/advanced-html-css/detailed-css-positioning'),
    (1, 2, 'Article', 'CSS Basics', 'Overview of CSS.', 'https://learnxinyminutes.com/docs/css'),
    (1, 2, 'Article', 'Specificity', 'Explanation of specificity in CSS.', 'https://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know'),
    (1, 2, 'Article', 'Responsive web design', 'Different methods to go about responsive design in web.', 'https://developers.google.com/web/fundamentals/design-and-ux/responsive/patterns'),
    (1, 1, 'Video', 'Recursion', 'How to implement recursion in Javascript.', 'https://www.youtube.com/watch?v=k7-N8R0-KY4'),
    (1, 1, 'Video', 'Promises', 'How to use promises in Javascript.', 'https://www.youtube.com/watch?v=2d7s3spWAzo'),
    (1, 1, 'Video', 'Closers', 'What are closures?', 'https://www.youtube.com/watch?v=CQqwU2Ixu-U'),
    (1, 2, 'Video', 'Architecture', 'How to build good CSS architecture.', 'https://www.youtube.com/watch?v=Nxnp-JLgo5I'),
    (1, 4, 'Video', 'Database design basics', 'Basic introduction to Sequel.', 'https://www.youtube.com/watch?v=LKZYoeRfmh4'),
    (1, 3, 'Video', 'Tags', 'Intro to tags in HTML.', 'https://www.youtube.com/watch?v=dmovVa0jseU'),
    (1, 2, 'Game', 'Learn Flexbox', 'Interactive game to learn how to use flexbox.', 'https://flexboxfroggy.com'),
    (1, 2, 'Game', 'Learn CSS grid', 'Interactive game to learn how to use css grid.', 'https://cssgridgarden.com'),
    (1, 1, 'Game', 'Elevator saga', 'Game to practise javascript skills.', 'http://play.elevatorsaga.com'),
    (1, 1, 'Game', 'Checkio Game', 'Games to practise javascript coding.', 'https://checkio.org'),
    (1, 2, 'Game', 'CSS DinerGame', 'Games to learn CSS.', 'https://flukeout.github.io'),
    (1, 1, 'Video', 'Learn JavaScript in 1 Hour', 'JavaScript Tutorial for Beginners.', 'https://www.youtube.com/watch?v=W6NZfCO5SIk'),
    (1, 1, 'Online Course', 'JavaScipt', 'JavaScript course for Beginners.', 'https://www.theodinproject.com/courses/javascript'),
    (1, 2, 'Online Course', 'CSS Into', 'Introduction to Basic CSS.', 'https://www.freecodecamp.org/learn/responsive-web-design/basic-css'),
    (1, 2, 'Video', 'CSS Grid', 'Grid template areas, columns, rows, and aligning items.', 'https://www.youtube.com/watch?v=EFafSYg-PkI'),
    (2, 3, 'Documentation', 'HTML Tutorial', 'Documentation of HTML on W3Schools.', 'https://www.w3schools.com/html'),
    (2, 4, 'Video', 'MySQL Tutorial for Beginners', 'Full Course on SQL.', 'https://youtu.be/7S_tz1z_5bA'),
    (2, 4, 'Interactive sandbox', 'SQL sandbox', 'SQL playground.', 'https://sqlzoo.net'),
    (2, 4, 'Article', 'SQL Join types', 'Explains the type of SQL join there are.', 'https://www.dofactory.com/sql/join'),
    (2, 1, 'Book', 'Eloquent JavaScript', 'This is a book about JavaScript and programming; Written by Marijn Haverbeke.', 'https://eloquentjavascript.net'),
    (2, 1, 'Article', 'Async/Await', 'An article on the Async and Await keyword in Javascript.', 'https://javascript.info/async-await'),
    (2, 1, 'Article', 'What arguments really mean', 'An article on the arguments object in Javascript.', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments'),
    (2, 1, 'Article', 'Scope me through the lens', 'Clear explanation of scopes in Javascript.', 'https://dev.to/sandy8111112004/javascript-introduction-to-scope-function-scope-block-scope-d11'),
    (2, 1, 'Article', 'This', 'An article on the ''This'' keyword in Javascript.', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this'),
    (2, 1, 'Article', 'Array.reduce()', 'An article on array.reduce method in Javascript.', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce'),
    (2, 1, 'Article', 'Object.entries() In JavaScript', 'An article on the Object.entries function in Javascript.', 'https://www.geeksforgeeks.org/object-entries-javascript'),
    (2, 3, 'Article', 'What is HTML?', 'An introductory article on HTML.', 'https://html.com'),
    (2, 3, 'Online Course', 'HTML course on codecademy', 'An introductory course on HTML.', 'https://www.codecademy.com/learn/learn-html'),
    (2, 2, 'Article', 'A Complete Guide to Flexbox', 'A comprehensive article on how to use css flexbox.', 'https://css-tricks.com/snippets/css/a-guide-to-flexbox'),
    (2, 2, 'Article', 'Pseudo-classes', 'Article on css pseudo-classes.', 'https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes'),
    (2, 1, 'Article', 'What time is it?', 'An article on the Javasript get date methods.', 'https://www.w3schools.com/js/js_date_methods.asp'),
    (2, 1, 'Article', 'Using requestAnimationFrame', 'An article on the request animation frame function.', 'https://css-tricks.com/using-requestanimationframe'),
    (2, 2, 'Article', 'Boxes', 'An comprehensive article on the box model.', 'https://www.w3schools.com/css/css_boxmodel.asp'),
    (2, 2, 'Documentation', 'CSS Bootstrap', 'An comprehensive documentation provided by bootstrap.', 'https://getbootstrap.com/docs/4.4/getting-started/introduction'),
    (2, 2, 'Online Course', 'CSS Basics course', 'An comprehensive CSS course provided by MIT and Harvard.', 'https://www.edx.org/course/css-basics'),
    (2, 2, 'Article', 'Using CSS animations', 'An comprehensive article on using CSS animations.', 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations'),
    (2, 2, 'Video', 'Learn CSS Position In 9 Minutes', 'Video explaining css positioning.', 'https://www.youtube.com/watch?v=jx5jmI0UlXU'),
    (2, 4, 'Documentation', 'Postgres Data with Node', 'Documentation on how to use postgres in node.', 'https://node-postgres.com'),
    (2, 1, 'Video', 'Prototypes', 'A video of Daniel explaining prototypes in Javascript.', 'https://www.youtube.com/watch?v=hS_WqkyUah8'),
    (2, 1, 'Video', 'var, let and const - What, why and how', 'A video of MPJ explaining var, let and const in Javascript.', 'https://www.youtube.com/watch?v=sjyJBL5fkp8'),
    (2, 1, 'Video', '=>', 'Arrows, Arrows, Arrows, Arrows, Arrows EVERYWHERE!!!', 'https://www.youtube.com/watch?v=mrYMzpbFz18');
